---
title: "demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(testthat)
library(prodigalr)
```

Input genome filename:

```{r}
fasta_filename <- system.file(
  "extdata", "covid19.fasta", package = "prodigalr"
)
```

```{r}
prodigal_options <- create_prodigal_options(
  fasta_filename = fasta_filename
)
```

```{r}
if (is_prodigal_installed()) {
  create_prodigal_files(prodigal_options)
}
```

1:

```{r}
if (is_prodigal_installed()) {
  cat(prodigal_options$output_filename)
  readLines(prodigal_options$output_filename)
}
```

2:

```{r}
if (is_prodigal_installed()) {
  cat(prodigal_options$trans_filename)
  readLines(prodigal_options$trans_filename)
}
```

3:

```{r}
if (is_prodigal_installed()) {
  cat(prodigal_options$nuc_filename)
  readLines(prodigal_options$nuc_filename)
}
```

4:

```{r}
if (is_prodigal_installed()) {
  cat(prodigal_options$start_filename)
  readLines(prodigal_options$start_filename)
}
```
